- id: '1'
  alias: Input_Number Change L
  trigger:
  - platform: state
    entity_id: climate.xx
  action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.xx
      temperature: '{{ (states.climate.xx.attributes.thermostat_target_temp|float) }}'
